export const consumerData = [
  {
    first_name: "John",
    middle_name: "Doe",
    last_name: "Smith",
    name: "John Doe Smith",
    contact_no: "+63916456545",
    address: "Cebu City",
    casureco_no: "4H5B77G",
    device_no: "7BKL44H",
    email: "john.doe@example.com",
    password: "password",
    voltage: "200",
    current: "42",
    kwh: "540",
    monthly_bill: "18500",
    previous_bill: "17200",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "Jane",
    middle_name: "Di",
    last_name: "Cruz",
    name: "Jane Di Cruz",
    contact_no: "+639087654321",
    address: "Mandaluyong City",
    casureco_no: "9X0EF1G",
    device_no: "8CLM55N",
    email: "jane.di@example.com",
    password: "password",
    voltage: "220",
    current: "38",
    kwh: "480",
    monthly_bill: "16000",
    previous_bill: "15200",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "Michael",
    middle_name: "Lee",
    last_name: " Reyes",
    name: "Michael Lee Reyes",
    contact_no: "+639198765432",
    address: "Makati City",
    casureco_no: "2LMNP3Q",
    device_no: "9DOOP66P",
    email: "michael.lee@example.com",
    password: "password",
    voltage: "231",
    current: "20",
    kwh: "240",
    monthly_bill: "8000",
    previous_bill: "7500",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "Sarah",
    middle_name: "May",
    last_name: "David",
    name: "Sarah May David",
    contact_no: "+639209876543",
    address: "Caloocan City",
    casureco_no: "5QRS6TQ",
    device_no: "0ERRS77U",
    email: "sarah.may@example.com",
    password: "password",
    voltage: "209",
    current: "25",
    kwh: "300",
    monthly_bill: "10500",
    previous_bill: "9800",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "David",
    middle_name: "John",
    last_name: "Tan",
    name: "David John Tan",
    contact_no: "+639210987654",
    address: "Marikina City",
    casureco_no: "VWXYZ1A",
    device_no: "1FTTU88V",
    email: "david.john@example.com",
    password: "password",
    voltage: "230",
    current: "18",
    kwh: "220",
    monthly_bill: "7200",
    previous_bill: "6800",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "Emily",
    middle_name: "Rose",
    last_name: "Garcia",
    name: "Emily Rose Garcia",
    contact_no: "+639221098765",
    address: "Parañaque City",
    casureco_no: "234567B",
    device_no: "2GGHH88I",
    email: "emily.rose@example.com",
    password: "password",
    voltage: "0",
    current: "22",
    kwh: "280",
    monthly_bill: "9500",
    previous_bill: "9000",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "William",
    middle_name: "Charles",
    last_name: "Lee",
    name: "William Charles Lee",
    contact_no: "+639231234567",
    address: "Pasig City",
    casureco_no: "890ABC3",
    device_no: "3HHII99J",
    email: "william.charles@example.com",
    password: "password",
    voltage: "230",
    current: "35",
    kwh: "420",
    monthly_bill: "14000",
    previous_bill: "13500",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "Olivia",
    middle_name: "Marie",
    last_name: "Cruz",
    name: "Olivia Marie Cruz",
    contact_no: "+639241345678",
    address: "San Juan City",
    casureco_no: "DEF123C",
    device_no: "4IIPP00K",
    email: "olivia.marie@example.com",
    password: "password",
    voltage: "220",
    current: "14",
    kwh: "160",
    monthly_bill: "6000",
    previous_bill: "5500",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "Matthew",
    middle_name: "Paul",
    last_name: " Reyes",
    name: "Matthew Paul Reyes",
    contact_no: "+639251456789",
    address: "Mandaluyong City",
    casureco_no: "GHI456D",
    device_no: "5JJQQ11L",
    email: "matthew.paul@example.com",
    password: "password",
    voltage: "0",
    current: "27",
    kwh: "340",
    monthly_bill: "11800",
    previous_bill: "11200",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "Ashley",
    middle_name: "Catherine",
    last_name: "Tan",
    name: "Ashley Catherine Tan",
    contact_no: "+639261567890",
    address: "Marikina City",
    casureco_no: "JKL789E",
    device_no: "6KKRR22M",
    email: "ashley.catherine@example.com",
    password: "password",
    voltage: "220",
    current: "19",
    kwh: "230",
    monthly_bill: "8200",
    previous_bill: "7700",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "Mark",
    middle_name: "Anthony",
    last_name: "Garcia",
    name: "Mark Anthony Garcia",
    contact_no: "+639271678901",
    address: "Navotas City",
    casureco_no: "MNO012F",
    device_no: "7LLSS33N",
    password: "password",
    voltage: "230",
    current: "29",
    kwh: "360",
    monthly_bill: "12500",
    previous_bill: "12000",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "Catherine",
    middle_name: "Beatrice",
    last_name: "Cruz",
    name: "Catherine Beatrice Cruz",
    contact_no: "+639281789012",
    address: "Muntinlupa City",
    casureco_no: "PQR345G",
    device_no: "8MMTT44O",
    password: "password",
    voltage: "230",
    current: "16",
    kwh: "190",
    monthly_bill: "6800",
    previous_bill: "6300",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "Daniel",
    middle_name: "John",
    last_name: " Reyes",
    name: "Daniel John Reyes",
    contact_no: "+639291890123",
    address: "Valenzuela City",
    casureco_no: "STU678H",
    device_no: "9NNUU55P",
    password: "password",
    voltage: "220",
    current: "31",
    kwh: "390",
    monthly_bill: "13800",
    previous_bill: "13300",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "Elizabeth",
    middle_name: "Christine",
    last_name: "Tan",
    name: "Elizabeth Christine Tan",
    contact_no: "+639302091234",
    address: "Malabon City",
    casureco_no: "VWX901I",
    device_no: "0OOXX66Q",
    password: "password",
    voltage: "230",
    current: "24",
    kwh: "300",
    monthly_bill: "10500",
    previous_bill: "10000",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
  {
    first_name: "William",
    middle_name: "David",
    last_name: "Garcia",
    name: "William David Garcia",
    contact_no: "+639312192345",
    address: "Las Piñas City",
    casureco_no: "YZABC2J",
    device_no: "1PPYY77R",
    password: "password",
    voltage: "220",
    current: "20",
    kwh: "250",
    monthly_bill: "8700",
    previous_bill: "8200",
    geolocation: [13.6258 + getRandomOffset(), 123.1945 + getRandomOffset()],
  },
];

export const postList = [
  [
    {
      id: 1,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliqua.",
      date: "03/03/2024",
      posted_by: "Admin Ballesteros",
      photo: null,
      images: ["https://placehold.co/400"],
      views: 366,
    },
    {
      id: 2,
      description:
        "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec ullamcorper nulla non metus auctor fringilla.",
      date: "03/03/2024",
      posted_by: "Admin Smith",
      photo: "https://placehold.co/600",
      images: [
        "https://placehold.co/400",
        "https://placehold.co/500",
        "https://placehold.co/700",
      ],
      views: 489,
    },
    {
      id: 3,
      description:
        "Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.",
      date: "03/03/2024",
      posted_by: "Admin Rodriguez",
      photo: "https://placehold.co/550",
      images: ["https://placehold.co/450"],
      views: 275,
    },
    {
      id: 4,
      description:
        "Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.",
      date: "03/03/2024",
      posted_by: "Admin Johnson",
      photo: "https://placehold.co/500",
      images: [
        "https://placehold.co/300",
        "https://placehold.co/350",
        "https://placehold.co/450",
      ],
      views: 621,
    },
    {
      id: 5,
      description:
        "Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.",
      date: "03/03/2024",
      posted_by: "Admin Lee",
      photo: "https://placehold.co/700",
      images: ["https://placehold.co/600"],
      views: 804,
    },
    {
      id: 6,
      description:
        "Nullam quis risus eget urna mollis ornare vel eu leo. Aenean lacinia bibendum nulla sed consectetur.",
      date: "03/03/2024",
      posted_by: "Admin Brown",
      photo: null,
      images: ["https://placehold.co/550"],
      views: 427,
    },
    {
      id: 7,
      description:
        "Integer posuere erat a ante venenatis dapibus posuere velit aliquet.",
      date: "03/03/2024",
      posted_by: "Admin Kim",
      photo: "https://placehold.co/800",
      images: [
        "https://placehold.co/700",
        "https://placehold.co/750",
        "https://placehold.co/900",
      ],
      views: 543,
    },
    {
      id: 8,
      description:
        "Etiam porta sem malesuada magna mollis euismod. Cras mattis consectetur purus sit amet fermentum.",
      date: "03/03/2024",
      posted_by: "Admin Martinez",
      photo: "https://placehold.co/650",
      images: ["https://placehold.co/500"],
      views: 312,
    },
    {
      id: 9,
      description:
        "Curabitur blandit tempus porttitor. Nulla vitae elit libero, a pharetra augue.",
      date: "03/03/2024",
      posted_by: "Admin Garcia",
      photo: null,
      images: ["https://placehold.co/450"],
      views: 198,
    },
    {
      id: 10,
      description:
        "Vestibulum id ligula porta felis euismod semper. Nullam id dolor id nibh ultricies vehicula ut id elit.",
      date: "03/03/2024",
      posted_by: "Admin Taylor",
      photo: "https://placehold.co/600",
      images: [
        "https://placehold.co/400",
        "https://placehold.co/550",
        "https://placehold.co/700",
      ],
      views: 537,
    },
  ],
];

export const admins = [
  {
    employee_id: "1HB4348",
    name: "John Admin Smith",
    email: "johnadmin@mail.com",
    contact_no: "0909090909",
    employee_type: "Supervisor",
  },
  {
    employee_id: "2AB5678",
    name: "Jane Manager Johnson",
    email: "janemanager@mail.com",
    contact_no: "0912345678",
    employee_type: "Manager",
  },
  {
    employee_id: "3CD9101",
    name: "Bob Worker Brown",
    email: "bobworker@mail.com",
    contact_no: "0987654321",
    employee_type: "Worker",
  },
  {
    employee_id: "4EF1122",
    name: "Alice Engineer White",
    email: "aliceengineer@mail.com",
    contact_no: "0976543210",
    employee_type: "Engineer",
  },
  {
    employee_id: "5GH3344",
    name: "Mark Developer Davis",
    email: "markdeveloper@mail.com",
    contact_no: "0943210987",
    employee_type: "Developer",
  },
];

export const announcementList = [
  {
    id: 1,
    title: "Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    date: "03/03/2024",
    posted_by: "Admin Smith",
    photo: "https://placehold.co/600",
  },
  {
    id: 2,
    title: "Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    date: "03/03/2024",
    posted_by: "Admin Smith",
    photo: "https://placehold.co/600",
  },
  {
    id: 3,
    title: "Announcement",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    date: "03/03/2024",
    posted_by: "Admin Smith",
    photo: "https://placehold.co/600",
  },
];

function getRandomOffset() {
  // Adjust the range as needed for your desired randomness
  return (Math.random() - 0.5) * 0.1; // Example: random offset between -0.05 and 0.05
}
